### PR TITLE
Add Job and Cron Job APIs and related tests

### PR DESCRIPTION
**Pull request by nmacherey**
The PR is in progress:

## Functional Evolutions
- [x] Add the Job API
- [x] Add tests for the Job API
- [x] Add the CronJob API
- [x] Add tests for the Cron Job API
- [x] Add JMS Serializer for Jobs and related Models
- [x] Add JMS Serializer for CronJobs and related Models

## Potential BC Breaks
- [x] Containers should be able to get arguments in the constructor. Commands are overriding the "ENTRYPOINT" while arguments are overiding de "CMD"
- [x] Add tests for arguments in the Job API

The PR includes this BC as arguments should be given right after the command in the Container constructor. The tests for commands are included into the job.feature

### CODE REVIEW

**Comment by sroze** [comment]
You forgot the JMS Serializer configurations for now, but, yep, definitely agree going forward this 👍

**Comment by nmacherey** [comment]
@sroze It is still a work in progress, as my knowledge of Kubernetes is very limited. Especially I have some question about the HttpJobRepository isPending and isTerminated method which should relies on properties given by the Job status. Anyway I am not sure about the logic in there.

I have taken quite the same features as in the pods fo testing as A job is a controller for Pods now. Tests are passing but we can add some additional features.

I will do some similar stuff into the CronJobRepository.

**Comment by nmacherey** [comment]
@sroze the PR is now complete waiting for your review

Regards

**Comment by sroze** [comment]
Wow, that's a great job @nmacherey 👏. I'll review this tomorrow. In the meantime, you have some small conflicts with `master`, could you fix them? Thanks!

**Comment by nmacherey** [comment]
@sroze sorry I did not notice your message. The master has been rebased so it should ne have all conflicts resolved

Regards !

**Comment by sroze** [comment]
Thank you @nmacherey!

**Pull request merged**
